/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as PortraitsRouteImport } from './routes/portraits'
import { Route as MuralsRouteImport } from './routes/murals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortraitsRoute = PortraitsRouteImport.update({
  id: '/portraits',
  path: '/portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralsRoute = MuralsRouteImport.update({
  id: '/murals',
  path: '/murals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/works/$slug',
  path: '/works/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/murals': typeof MuralsRoute
  '/portraits': typeof PortraitsRoute
  '/weddings': typeof WeddingsRoute
  '/works/$slug': typeof WorksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/murals': typeof MuralsRoute
  '/portraits': typeof PortraitsRoute
  '/weddings': typeof WeddingsRoute
  '/works/$slug': typeof WorksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/murals': typeof MuralsRoute
  '/portraits': typeof PortraitsRoute
  '/weddings': typeof WeddingsRoute
  '/works/$slug': typeof WorksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/murals'
    | '/portraits'
    | '/weddings'
    | '/works/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/murals'
    | '/portraits'
    | '/weddings'
    | '/works/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/murals'
    | '/portraits'
    | '/weddings'
    | '/works/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MuralsRoute: typeof MuralsRoute
  PortraitsRoute: typeof PortraitsRoute
  WeddingsRoute: typeof WeddingsRoute
  WorksSlugRoute: typeof WorksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portraits': {
      id: '/portraits'
      path: '/portraits'
      fullPath: '/portraits'
      preLoaderRoute: typeof PortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/murals': {
      id: '/murals'
      path: '/murals'
      fullPath: '/murals'
      preLoaderRoute: typeof MuralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/works/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MuralsRoute: MuralsRoute,
  PortraitsRoute: PortraitsRoute,
  WeddingsRoute: WeddingsRoute,
  WorksSlugRoute: WorksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
